### ISSUE TITLE
CSVs and XLSX alignment

### ISSUE THREAD

**Issue by bmschmidt** [cestastanford/historical-us-city-populations#5]
The csv and xlsx files here appear to be out of alignment: the last commit seems to have pushed a lot of new Arkansas and Colorado data (at least) to the xlsx but not to the csv.

Probably there should only be a single "Master" file?

**Comment by hepplerj** [comment]
I agree, we should follow a Master file. I'd argue it's best we do away entirely with the xlsx file, but I'd have to leave that determination up to @cartosattva. 

Otherwise, maybe we could mirror these a bit better via Make or something (and provide an additional SQLite db along with the csv and xlsx).

**Comment by cartosattva** [comment]
Makes sense; I have deleted the xlsx file.
